# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 234)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(380, 234))
        Form.setMaximumSize(QtCore.QSize(380, 234))
        font = QtGui.QFont()
        font.setBold(True)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/ecust.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.ecustLogo = QtWidgets.QLabel(Form)
        self.ecustLogo.setGeometry(QtCore.QRect(10, 0, 61, 71))
        self.ecustLogo.setText("")
        self.ecustLogo.setPixmap(QtGui.QPixmap("image/ecust.png"))
        self.ecustLogo.setObjectName("ecustLogo")
        self.boxTitle = QtWidgets.QLabel(Form)
        self.boxTitle.setGeometry(QtCore.QRect(70, 20, 291, 51))
        self.boxTitle.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.boxTitle.setScaledContents(False)
        self.boxTitle.setObjectName("boxTitle")
        self.edtUsername = QtWidgets.QLineEdit(Form)
        self.edtUsername.setGeometry(QtCore.QRect(140, 80, 113, 21))
        self.edtUsername.setInputMask("")
        self.edtUsername.setObjectName("edtUsername")
        self.edtPassword = QtWidgets.QLineEdit(Form)
        self.edtPassword.setGeometry(QtCore.QRect(140, 120, 113, 21))
        self.edtPassword.setInputMask("")
        self.edtPassword.setClearButtonEnabled(False)
        self.edtPassword.setObjectName("edtPassword")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(160, 160, 71, 32))
        self.loginButton.setObjectName("loginButton")
        self.loginButton_2 = QtWidgets.QPushButton(Form)
        self.loginButton_2.setGeometry(QtCore.QRect(160, 190, 71, 32))
        self.loginButton_2.setObjectName("loginButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "用户登陆"))
        self.boxTitle.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:700; color:#003588;\">xx智能生产调度处理工具</span></p></body></html>"))
        self.edtUsername.setPlaceholderText(_translate("Form", "username"))
        self.edtPassword.setPlaceholderText(_translate("Form", "password"))
        self.loginButton.setText(_translate("Form", "Login"))
        self.loginButton_2.setText(_translate("Form", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
