# Form implementation generated from reading ui file 'signUp.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget.sizePolicy().hasHeightForWidth())
        widget.setSizePolicy(sizePolicy)
        widget.setMinimumSize(QtCore.QSize(400, 300))
        widget.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/ecust.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        widget.setWindowIcon(icon)
        self.signupButton = QtWidgets.QPushButton(widget)
        self.signupButton.setGeometry(QtCore.QRect(150, 190, 101, 32))
        self.signupButton.setObjectName("signupButton")
        self.adtUsername = QtWidgets.QLineEdit(widget)
        self.adtUsername.setGeometry(QtCore.QRect(140, 90, 121, 31))
        self.adtUsername.setObjectName("adtUsername")
        self.edtPassword = QtWidgets.QLineEdit(widget)
        self.edtPassword.setGeometry(QtCore.QRect(140, 140, 121, 31))
        self.edtPassword.setObjectName("edtPassword")
        self.ecust = QtWidgets.QLabel(widget)
        self.ecust.setGeometry(QtCore.QRect(10, 0, 61, 61))
        self.ecust.setText("")
        self.ecust.setPixmap(QtGui.QPixmap("image/ecust.png"))
        self.ecust.setObjectName("ecust")
        self.title = QtWidgets.QLabel(widget)
        self.title.setGeometry(QtCore.QRect(140, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setObjectName("title")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "用户注册"))
        self.signupButton.setText(_translate("widget", "Sign up"))
        self.adtUsername.setPlaceholderText(_translate("widget", "Username"))
        self.edtPassword.setPlaceholderText(_translate("widget", "Password"))
        self.title.setText(_translate("widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#00408e;\">用户注册</span></p></body></html>"))
